---
image: golang:latest
stages:
  - lint
  - test
  # - package
  # - release
include:
  - template: Jobs/SAST.gitlab-ci.yml
#  - template: Code-Quality.gitlab-ci.yml
lua-check:
  stage: lint
  image:
    name: ghcr.io/lunarmodules/luacheck:latest
    entrypoint:
      - ""    
  script:
    - luacheck .
sonarqube-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint:
      - ""
  variables:
    SONAR_USER_HOME: ${CI_PROJECT_DIR}/.sonar
    GIT_DEPTH: "0"
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - merge_requests
    - master
    - main
    - develop