on:
  push:
    tags:
      - "*.*.*"
permissions:
  contents: write

jobs:
  lint_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1.1.1

      - name: Bump version
        env:
          VERSION: ${{github.ref_name}}
        run: make bump
              
      - name: Package for github release
        env:
          VERSION: ${{github.ref_name}}
        run: make zip

      - name: Changelog
        uses: addnab/docker-run-action@v3
        with:
          image: quay.io/git-chglog/git-chglog
          options: -v ${{ github.workspace }}:/workdir
          run: git-chglog --output CHANGELOG-${{github.ref_name}}.md ${{github.ref_name}}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: memento-${{github.ref_name}}.zip
          body_path: CHANGELOG-${{github.ref_name}}.md


      - name: Upload the mod to Steam Workshop (if this is a release commit)
        uses: IsaacScript/isaac-steam-workshop-upload@v1
        if: "contains(github.event.head_commit.message, 'chore: release') && github.event_name != 'pull_request'"
        with:
          mod_path: .
          ignore_files: Makefile
          change_note: "Version: {VERSION}\n\nChanges for this mod are [url=https://github.com/h-4-t/memento-mod/releases]tracked on GitHub[/url]."
        env:
          CONFIG_VDF_CONTENTS: ${{ secrets.CONFIG_VDF_CONTENTS }}